# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=2047, null=True),
        ),
    ]
